name: Python package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: |
        echo "$pythonVersion = (python --version)" >> $GITHUB_OUTPUT
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pylint mypy
    - name: Run black
      run:
        black --check .
    - name: Run Pylint
      run: pylint
    - name: Run Mypy
      run: mypy retinaface
    - name: tests
      run: |
        pip install .[tests]
        pytest  
