- name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pylint mypy
    - name: Run black
      run:
        black --check .
    - name: Run Pylint
      run: pylint
    - name: Run Mypy
      run: mypy retinaface
